// Code generated by "stringer -output=strings.go -type=Command,Status"; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdDeviceState-7]
	_ = x[CmdChangeNetworkState-8]
	_ = x[CmdReadParameter-10]
	_ = x[CmdWriteParameter-11]
	_ = x[CmdDeviceStateChanged-14]
	_ = x[CmdVersion-13]
	_ = x[CmdAPSDataRequest-18]
	_ = x[CmdAPSDataConfirm-4]
	_ = x[CmdAPSDataIndication-23]
	_ = x[CmdMacPollIndication-28]
	_ = x[CmdMacBeaconIndication-31]
	_ = x[CmdUpdateBootloader-33]
	_ = x[CmdUpdateNeighbor-29]
	_ = x[CmdGreenPower-25]
}

const (
	_Command_name_0 = "CmdAPSDataConfirm"
	_Command_name_1 = "CmdDeviceStateCmdChangeNetworkState"
	_Command_name_2 = "CmdReadParameterCmdWriteParameter"
	_Command_name_3 = "CmdVersionCmdDeviceStateChanged"
	_Command_name_4 = "CmdAPSDataRequest"
	_Command_name_5 = "CmdAPSDataIndication"
	_Command_name_6 = "CmdGreenPower"
	_Command_name_7 = "CmdMacPollIndicationCmdUpdateNeighbor"
	_Command_name_8 = "CmdMacBeaconIndication"
	_Command_name_9 = "CmdUpdateBootloader"
)

var (
	_Command_index_1 = [...]uint8{0, 14, 35}
	_Command_index_2 = [...]uint8{0, 16, 33}
	_Command_index_3 = [...]uint8{0, 10, 31}
	_Command_index_7 = [...]uint8{0, 20, 37}
)

func (i Command) String() string {
	switch {
	case i == 4:
		return _Command_name_0
	case 7 <= i && i <= 8:
		i -= 7
		return _Command_name_1[_Command_index_1[i]:_Command_index_1[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _Command_name_2[_Command_index_2[i]:_Command_index_2[i+1]]
	case 13 <= i && i <= 14:
		i -= 13
		return _Command_name_3[_Command_index_3[i]:_Command_index_3[i+1]]
	case i == 18:
		return _Command_name_4
	case i == 23:
		return _Command_name_5
	case i == 25:
		return _Command_name_6
	case 28 <= i && i <= 29:
		i -= 28
		return _Command_name_7[_Command_index_7[i]:_Command_index_7[i+1]]
	case i == 31:
		return _Command_name_8
	case i == 33:
		return _Command_name_9
	default:
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusSuccess-0]
	_ = x[StatusFailure-1]
	_ = x[StatusBusy-2]
	_ = x[StatusTimeout-3]
	_ = x[StatusUnsupported-4]
	_ = x[StatusError-5]
	_ = x[StatusNoNetwork-6]
	_ = x[StatusInvalidValue-7]
}

const _Status_name = "StatusSuccessStatusFailureStatusBusyStatusTimeoutStatusUnsupportedStatusErrorStatusNoNetworkStatusInvalidValue"

var _Status_index = [...]uint8{0, 13, 26, 36, 49, 66, 77, 92, 110}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
